-- Use an integer identity to avoid requiring extensions.
create table if not exists public.generations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  property_type text not null,
  location text,
  price_range text,
  features text,
  tone text,
  description text,
  social_post text,
  hashtags text[]
);

-- Helpful index for search
create index if not exists idx_generations_location on public.generations using gin (to_tsvector('simple', coalesce(location, '')));
create index if not exists idx_generations_features on public.generations using gin (to_tsvector('simple', coalesce(features, '')));
